# Generated by Django 4.0.1 on 2022-02-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='booked_service', to='app.servicemodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderItemModel',
        ),
    ]
