# Generated by Django 4.0.1 on 2022-02-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_ordermodel_service_delete_orderitemmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='coupon_applied',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='total_price',
        ),
    ]
