# Generated by Django 4.0.1 on 2022-02-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloonmodel',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='authentication.sellermodel'),
        ),
    ]
